# Autogenerated by nbdev

d = { 'settings': { 'branch': 'master',
                'doc_baseurl': '/nbdev-project-01',
                'doc_host': 'https://HaiNguyen007.github.io',
                'git_url': 'https://github.com/HaiNguyen007/nbdev-project-01',
                'lib_path': 'nbdev_project_01'},
  'syms': {'nbdev_project_01.core': {'nbdev_project_01.core.foo': ('core.html#foo', 'nbdev_project_01/core.py')}}}